#!/usr/bin/env python

'''Usage:
            filtr -x <expression> [datafile>] [--limit <max_records>]
         
'''

#
# filtr: command line utility for filtering record streams
#


import docopt
from docopt import docopt as docopt_func
from docopt import DocoptExit
import os, sys
import csv
import json
from snap import snap, common
from mercury import datamap as dmap
import yaml
import logging



def main(args):
    print(common.jsonpretty(args))


if __name__ == '__main__':
    args = docopt.docopt(__doc__)
    main(args)
