#!/usr/bin/env python

'''
Usage:
  mercman --list
  mercman <command>

Options:
  -l --list       show the available man pages
'''

import os, sys
import json
import docopt




def main(args):
    pass


if __name__ == '__main__':
    args = docopt.docopt(__doc__)
    main(args)

