#!/usr/bin/env python

'''
Usage:
    pause <pause_time_seconds>

'''

import os, sys
import time
import docopt


def main(args):
    delay_time = int(args['<pause_time_seconds>'])

    if delay_time == 0:
        return

    if delay_time < 0:
        raise Exception('The delay time must be a positive integer.')

    print(f'Pausing for {delay_time} seconds.')
    time_remaining = delay_time
    clock = [t for t in range(time_remaining, 0, -1)]

    for timeval in clock:        
        print(f'{timeval} seconds remaining...')
        time.sleep(1)
    
    print('Done.')



if __name__ == '__main__':
    args = docopt.docopt(__doc__)
    main(args)